




.build/mega2560/src/DS18S20.cpp : src/DS18S20.ino
	@mkdir -p .build/mega2560/src
	@echo [93msrc/DS18S20.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/mega2560/src/DS18S20.cpp
	@true

